# Generated by Django 5.1.2 on 2024-10-22 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occupations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='occupations.group'),
        ),
        migrations.AddField(
            model_name='occupation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occupations.team'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'group')},
        ),
    ]
