# Generated by Django 5.1.2 on 2024-10-23 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='occupations.group'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='occupations.team'),
        ),
    ]
