# Generated by Django 5.1.2 on 2024-10-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0003_alter_occupation_group_alter_occupation_team'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='occupation',
            table='user_occupation',
        ),
    ]
