# Generated by Django 5.0.7 on 2024-08-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_initial'),
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMail',
            new_name='UserEmail',
        ),
    ]
