# Generated by Django 5.0.7 on 2024-09-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postboxes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbox',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
