# Generated by Django 5.1.2 on 2024-10-24 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postboxes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postbox',
            name='description',
        ),
    ]
