# Generated by Django 5.1.2 on 2024-10-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postboxes', '0003_remove_postbox_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbox',
            name='type',
            field=models.CharField(choices=[('default', 'Default'), ('custom', 'Custom')], default='default', max_length=7),
            preserve_default=False,
        ),
    ]
