# Generated by Django 5.1.2 on 2024-11-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postboxes', '0004_postbox_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postbox',
            options={'verbose_name_plural': 'postboxes'},
        ),
    ]
