# Generated by Django 5.0.7 on 2024-09-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='type',
            field=models.CharField(choices=[('type1', 'Type1'), ('type2', 'Type2')], max_length=5, null=True),
        ),
    ]
