# Generated by Django 5.1.2 on 2024-10-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='primary_email',
            field=models.EmailField(default=None, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_email',
            field=models.EmailField(default=None, max_length=254, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='EmailAddress',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
