# Generated by Django 5.0.7 on 2024-08-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=150)),
                ('from_addr', models.CharField(max_length=25)),
                ('from_service', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('read', 'Read'), ('unread', 'Unread')], default='unread', max_length=6)),
            ],
            options={
                'db_table': 'in_mails',
            },
        ),
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mail_attachment', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mail_attachments',
            },
        ),
        migrations.CreateModel(
            name='MailBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mail_body', models.TextField()),
            ],
            options={
                'db_table': 'mail_body',
            },
        ),
        migrations.CreateModel(
            name='OutMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=150)),
                ('to_addr', models.CharField(max_length=25)),
                ('to_service', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('writing', 'Writing'), ('pending', 'Pend'), ('fail', 'Fail'), ('sent', 'Sent')], default='writing', max_length=7)),
            ],
            options={
                'db_table': 'out_mail',
            },
        ),
    ]
