# Generated by Django 5.0.7 on 2024-08-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mails', '0001_initial'),
        ('postboxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmail',
            name='mail_box',
            field=models.ManyToManyField(related_name='in_mail', to='postboxes.postbox'),
        ),
    ]
