# Generated by Django 5.0.7 on 2024-08-05 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mails', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmail',
            name='recipient',
            field=models.ManyToManyField(related_name='in_mail', to='users.useremail'),
        ),
        migrations.AddField(
            model_name='inmail',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.useremail'),
        ),
        migrations.AddField(
            model_name='inmail',
            name='mail_attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_mail', to='mails.mailattachment'),
        ),
        migrations.AddField(
            model_name='inmail',
            name='mail_body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_mail', to='mails.mailbody'),
        ),
        migrations.AddField(
            model_name='outmail',
            name='mail_attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='out_mail', to='mails.mailattachment'),
        ),
        migrations.AddField(
            model_name='outmail',
            name='mail_body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='out_mail', to='mails.mailbody'),
        ),
        migrations.AddField(
            model_name='outmail',
            name='recipient',
            field=models.ManyToManyField(to='users.useremail'),
        ),
        migrations.AddField(
            model_name='outmail',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='out_mail', to='users.useremail'),
        ),
    ]
