# Generated by Django 5.1.2 on 2024-11-04 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='status',
        ),
        migrations.CreateModel(
            name='EmailReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('read', 'Read'), ('unread', 'Unread')], default='unread', max_length=6)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_status', to='emails.email')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_status', to='emails.emailrecipient')),
            ],
            options={
                'db_table': 'read_status',
                'unique_together': {('email', 'recipient')},
            },
        ),
    ]
