# Generated by Django 5.1.2 on 2024-11-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_remove_email_status_emailreadstatus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailreadstatus',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='emailreadstatus',
            constraint=models.UniqueConstraint(fields=('email', 'recipient'), name='unique_email_recipient'),
        ),
    ]
